services:
  dqanalyzer:
    build: .
    ports:
      - "9090:3000"
    environment:
      - DQAPI_HOST
      - DQTRANSLATOR_HOST

  # dqanalyzer-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev
  #   ports:
  #     - "9090:3000"
  #   environment:
  #     - DQAPI_HOST
  #     - DQTRANSLATOR_HOST
  #   volumes:
  #     - ./:/app