export enum WorkObjectType {
  CALL = "Call",
  CAR = "Car",
  DATA = "Data",
  DOCUMENT = "Document",
  EURO = "Euro",
  FOLDER = "Folder",
  HAMMER = "Hammer",
  MESSAGE = "Mesage",
  MISC = "Misc",
  PERSON = "Person",
  RATING = "Rating",
  SHIELD = "Shield",
  SYSTEM = "System",
}
